# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'zcsub-AzureARM'
    subscriptionId: '3ed4f01f-6e27-4724-93bf-e1001f78a63f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'NorwayRG'
    location: 'Norway East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/zacabrer/vnet/main/DefaultVnetTemplate.json'
    deploymentMode: 'Incremental'